source "tickle.tcl"
source "scripts/namespace.tcl"
source "scripts/timers.tcl"
source "scripts/misc.tcl"
source "scripts/variables.tcl"
source "scripts/channel.tcl"
source "scripts/usys.tcl"
source "scripts/pushmode.tcl"
source "scripts/bind.tcl"
source "scripts/usys.tcl"

#source "scripts/tcl.tcl"
#source "scripts/control.tcl"